Repository KostaMiniProject/MainProject-Back, pull requests merged in 2023-12, with the labels that each got.

#81 Feat : Bid 관련 응답 데이터 수정, 찜 기능 구현 완료
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidDeleteDTO.java
  src/main/java/kosta/main/bids/dto/BidListDTO.java
  src/main/java/kosta/main/bids/dto/BidListResponseDTO.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/dibs/controller/DibsController.java
  src/main/java/kosta/main/dibs/dto/DibRequestDto.java
  src/main/java/kosta/main/dibs/entity/Dib.java
  src/main/java/kosta/main/dibs/repository/DibsRepository.java
  src/main/java/kosta/main/dibs/service/DibsService.java
  src/main/java/kosta/main/dibs/testfile.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
Labels: 기능추가, 기능개선, Backend, 창민

#82 41 feat spring security jwt 구현
  build.gradle
  src/main/java/kosta/main/HealthController.java
  src/main/java/kosta/main/MainApplication.java
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/global/audit/Auditable.java
  src/main/java/kosta/main/global/config/SecurityConfig.java
  src/main/java/kosta/main/global/s3upload/S3Client.java
  src/main/java/kosta/main/items/entity/Item.java
  src/main/java/kosta/main/users/auth/CustomUserDetails.java
  src/main/java/kosta/main/users/auth/dto/LoginDto.java
  src/main/java/kosta/main/users/auth/handler/MemberAuthenticationFailureHandler.java
  src/main/java/kosta/main/users/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/kosta/main/users/auth/jwt/TokenProvider.java
  src/main/java/kosta/main/users/auth/service/CustomUserDetailsService.java
  src/main/java/kosta/main/users/controller/LoginController.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/UserCreateDto.java
  src/main/java/kosta/main/users/entity/Role.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/repository/UsersRepository.java
  src/main/java/kosta/main/users/repository/UsersRepositoryCustom.java
  src/main/java/kosta/main/users/repository/UsersRepositoryImpl.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/test/java/kosta/main/users/controller/UsersControllerTest.java
  src/test/java/kosta/main/users/service/UsersServiceTest.java
Labels: 기능추가, Backend

#87 Feat: JWT 상세 구현
  src/main/java/kosta/main/global/config/SecurityConfig.java
  src/main/java/kosta/main/users/auth/CustomUserDetails.java
  src/main/java/kosta/main/users/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/kosta/main/users/auth/jwt/JwtVerificationFilter.java
  src/main/java/kosta/main/users/auth/service/CustomUserDetailsService.java
  src/main/java/kosta/main/users/controller/LoginController.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/entity/LoginUser.java
  src/main/java/kosta/main/users/entity/UserAdapter.java
Labels: 기능추가, 성수, Backend

#88 Feat: JWT 구현으로인한 로직 변경 반영
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/test/java/kosta/main/users/controller/UsersControllerTest.java
  src/test/java/kosta/main/users/service/UsersServiceTest.java
Labels: 기능개선, 성수, Backend

#90 Feat: SQLDelete, Where 설정
  src/main/java/kosta/main/comments/entity/Comment.java
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능개선, 성수, Backend

#93 Feat: ImageService 정상 주소 저장하도록 변경
  src/main/java/kosta/main/global/s3upload/service/ImageService.java
Labels: 기능개선, 성수, Backend

#101 Feat: user 생성시 기본 프로필 이미지 업로드 하도록 변경
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, 성수, Backend

#105 Feat: Login시 UserId전달하도록 수정
  build.gradle
  src/main/java/kosta/main/global/dto/LoginResponse.java
  src/main/java/kosta/main/users/auth/jwt/JwtAuthenticationFilter.java
Labels: 기능개선, 성수, Backend

#112 Feat : Item(Create, Delete, Update)에 User 검증로직 추가 외 3개
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/dibs/controller/DibsController.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemUpdateResponseDto.java
  src/main/java/kosta/main/items/entity/Item.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/resources/static/communityPost.html
  src/main/resources/static/exchangePost.html
  src/main/resources/static/index.html
  src/main/resources/static/user.html
Labels: 기능개선, Backend, 창민

#120 Fix: 에러 발생부분 수정
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
Labels: 성수, Backend

#117 [Feat] @LoginUser 기반으로 변경
  src/main/java/kosta/main/reviews/controller/ReviewsController.java
  src/main/java/kosta/main/reviews/service/ReviewsService.java
Labels: 기능추가, Backend, 윤진

#124 83 feat user 관련 리뷰 작성하기 기능 추가 1
  src/main/java/kosta/main/reviews/dto/ReviewSaveDto.java
  src/main/java/kosta/main/reviews/service/ReviewsService.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, 기능개선, Backend, 윤진

#125 [Feat] 리뷰 기능 api 명세 수정(/users/reviews -> /api/reviews)
  src/main/java/kosta/main/reviews/controller/ReviewsController.java
Labels: 기능개선, Backend, 윤진

#126 119 fix 에러부분 점검 3
  src/docs/asciidoc/index.adoc
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemDetailResponseDTO.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/java/kosta/main/reviews/controller/ReviewsController.java
  src/main/java/kosta/main/reviews/dto/ReviewSaveDTO.java
  src/main/java/kosta/main/reviews/service/ReviewsService.java
  src/main/java/kosta/main/users/dto/UserItemResponseDTO.java
  src/test/java/kosta/main/reviews/ReviewStubData.java
  src/test/java/kosta/main/reviews/controller/ReviewsControllerTest.java
Labels: 성수, Backend

#128 119 fix 에러부분 점검 3
  src/docs/asciidoc/index.adoc
Labels: 성수, Backend, 테스트

#130 Feat: 에러 처리 구현
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/dibs/service/DibsService.java
  src/main/java/kosta/main/exchangehistories/testfile.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/global/error/dto/ErrorBaseResponse.java
  src/main/java/kosta/main/global/error/exception/BusinessException.java
  src/main/java/kosta/main/global/error/exception/ErrorCode.java
  src/main/java/kosta/main/global/error/exception/UnauthorizedException.java
  src/main/java/kosta/main/global/error/handler/GlobalExceptionHandler.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/java/kosta/main/users/auth/service/CustomUserDetailsService.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/test/java/kosta/main/reviews/controller/ReviewsControllerTest.java
Labels: 성수, Backend

#132 118 feat 물건 목록 페이지네이션 기능 추가 2
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemPageDTO.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/test/java/kosta/main/items/controller/ItemsControllerTest.java
Labels: 기능추가, 기능개선, Backend, 윤진

#137 [Feat] ItemDto -> ItemDTO로 변경
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/service/ItemsService.java
Labels: 기능추가, 기능개선, Backend, 윤진

#143 135 feat item user 관련 validation 적용 1
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemSaveDTO.java
  src/main/java/kosta/main/items/service/ItemsService.java
Labels: 기능추가, 기능개선, Backend, 윤진

#145 Feat : 채팅관련 기능 구현 1일차
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/dto/ChatRoomResponseDTO.java
  src/main/java/kosta/main/chatrooms/dto/CreateChatRoomDTO.java
  src/main/java/kosta/main/chatrooms/dto/CreateChatRoomResponseDTO.java
  src/main/java/kosta/main/chatrooms/entity/ChatRoom.java
  src/main/java/kosta/main/chatrooms/repository/ChatRoomsRepository.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/chats/controller/ChatsController.java
  src/main/java/kosta/main/chats/dto/ChatMessageDTO.java
  src/main/java/kosta/main/chats/service/ChatsService.java
Labels: 기능추가, Backend, 창민

#147 135 feat item user 관련 validation 적용 2
  src/main/java/kosta/main/global/error/dto/ErrorBaseResponse.java
  src/main/java/kosta/main/global/error/dto/ErrorValidationResponse.java
  src/main/java/kosta/main/global/error/handler/GlobalExceptionHandler.java
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemSaveDTO.java
Labels: 기능추가, 기능개선, Backend, 윤진

#150 135 feat item user 관련 validation 적용 3
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemSaveDTO.java
  src/main/java/kosta/main/items/dto/ItemUpdateDTO.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/UserCreateDTO.java
Labels: 기능추가, 기능개선, Backend, 윤진

#156 135 feat item user 관련 validation 적용 4
  src/main/java/kosta/main/items/dto/ItemSaveDTO.java
  src/main/java/kosta/main/items/dto/ItemUpdateDTO.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/UserCreateDTO.java
  src/main/java/kosta/main/users/dto/UserUpdateDTO.java
Labels: 기능추가, 기능개선, Backend, 윤진

#162 [Feat] 실시간 채팅 내역 응답, 읽음 상태 처리
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/dto/ChatListResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/chats/controller/ChatsController.java
  src/main/java/kosta/main/chats/dto/ChatMessageResponseDTO.java
  src/main/java/kosta/main/chats/entity/Chat.java
  src/main/java/kosta/main/chats/repository/ChatsRepository.java
  src/main/java/kosta/main/chats/service/ChatsService.java
Labels: 기능추가, Backend, 창민

#164 Feat: 대댓글 기능 구현
  src/main/java/kosta/main/comments/controller/CommentsController.java
  src/main/java/kosta/main/comments/dto/CommentCreateDTO.java
  src/main/java/kosta/main/comments/dto/CommentDTO.java
  src/main/java/kosta/main/comments/dto/CommentListDTO.java
  src/main/java/kosta/main/comments/entity/Comment.java
  src/main/java/kosta/main/comments/repository/CommentsRepository.java
  src/main/java/kosta/main/comments/repository/CommentsRepositoryCustom.java
  src/main/java/kosta/main/comments/repository/CommentsRepositoryImpl.java
  src/main/java/kosta/main/comments/service/CommentsService.java
  src/main/java/kosta/main/comments/testfile.java
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/global/error/exception/CommonErrorCode.java
Labels: 기능추가, 성수, Backend

#167 [Feat] 검색 결과 리스트 중 ItemStatus가 PUBLIC인 것만 필터링
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/entity/Item.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
Labels: 기능추가, 기능개선, Backend, 윤진

#171 Fix, Test: 전체 점검 및 테스트 코드 추가
  src/docs/asciidoc/index.adoc
  src/main/java/kosta/main/comments/controller/CommentsController.java
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDetailDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemDetailResponseDTO.java
  src/main/java/kosta/main/items/dto/ItemPageDTO.java
  src/main/java/kosta/main/likes/dto/LikeDTO.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/test/java/kosta/main/comments/controller/CommentStubData.java
  src/test/java/kosta/main/comments/controller/CommentsControllerTest.java
  src/test/java/kosta/main/communityposts/CommentStubData.java
  src/test/java/kosta/main/communityposts/CommunityPostStubData.java
  src/test/java/kosta/main/communityposts/controller/CommunityPostsControllerTest.java
  src/test/java/kosta/main/dibs/DibStubData.java
  src/test/java/kosta/main/dibs/controller/DibsControllerTest.java
  src/test/java/kosta/main/exchangeposts/ExchangePostStubData.java
  src/test/java/kosta/main/exchangeposts/controller/ExchangePostsControllerTest.java
  src/test/java/kosta/main/items/ItemStubData.java
  src/test/java/kosta/main/items/controller/ItemsControllerTest.java
  src/test/java/kosta/main/reviews/controller/ReviewsControllerTest.java
  src/test/java/kosta/main/users/controller/UsersControllerTest.java
Labels: 기능개선, 성수, Backend, 테스트

#176 Fix: ExchangePost 변경
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDetailDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/test/java/kosta/main/exchangeposts/ExchangePostStubData.java
  src/test/java/kosta/main/exchangeposts/controller/ExchangePostsControllerTest.java
  src/test/java/kosta/main/items/controller/ItemsControllerTest.java
Labels: 기능개선, 성수, Backend

#179 Fix: Authorization을 쿠키로 보내도록 변경
  src/main/java/kosta/main/users/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/kosta/main/users/auth/jwt/JwtVerificationFilter.java
Labels: 기능개선, 성수, Backend

#188 Feat : 채팅 기능 데이터 변경 및 쿠키 인증 방식 변경
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/dto/ChatRoomEnterResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/chats/controller/ChatsController.java
  src/main/java/kosta/main/chats/dto/ChatMessageDTO.java
  src/main/java/kosta/main/chats/dto/ChatMessageResponseDTO.java
  src/main/java/kosta/main/chats/entity/Chat.java
  src/main/java/kosta/main/chats/service/ChatsService.java
  src/main/java/kosta/main/exchangehistories/controller/ExchangeHistoriesController.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoriesResponseDto.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryResponseDto.java
  src/main/java/kosta/main/users/auth/jwt/JwtVerificationFilter.java
Labels: 기능추가, 기능개선, Backend, 창민

#189 Fix : 채팅목록 조회시 응답데이터에 chatRoomId 포함
  src/main/java/kosta/main/chatrooms/dto/ChatRoomResponseDTO.java
  src/main/java/kosta/main/exchangehistories/controller/ExchangeHistoriesController.java
  src/main/java/kosta/main/exchangehistories/repository/ExchangeHistoriesRepository.java
  src/main/java/kosta/main/exchangehistories/service/ExchangeHistoriesService.java
Labels: wontfix, Backend, 창민

#187 Feat: 물건 검색 PageNation
  src/main/java/kosta/main/global/dto/PageInfo.java
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/java/kosta/main/users/dto/UserItemResponseDTO.java
  src/test/java/kosta/main/items/controller/ItemsControllerTest.java
Labels: 기능개선, 성수, Backend

#191 190 feat 커뮤니티 검색 페이지네이션
  src/docs/asciidoc/index.adoc
  src/main/java/kosta/main/bids/dto/BidsDTO.java
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/repository/CommunityPostsRepository.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/test/java/kosta/main/communityposts/controller/CommunityPostsControllerTest.java
Labels: 기능개선, 성수, Backend

#194 Fix : 채팅 상세 조회시 ExchangePost 관련 데이터 추가
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/chatrooms/dto/ChatRoomEnterResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/exchangehistories/controller/ExchangeHistoriesController.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoriesResponseDTO.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoriesResponseDto.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryCreateDTO.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryCreateResponseDTO.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryResponseDTO.java
  src/main/java/kosta/main/exchangehistories/entity/ExchangeHistory.java
  src/main/java/kosta/main/exchangehistories/repository/ExchangeHistoriesRepository.java
  src/main/java/kosta/main/exchangehistories/service/ExchangeHistoriesService.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: wontfix, Backend, 창민

#199 163 feat 교환게시글 카테고리 추가 및 검색 기능 추가
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/chats/controller/ChatsController.java
  src/main/java/kosta/main/chats/dto/ChatMessageResponseDTO.java
  src/main/java/kosta/main/chats/service/ChatsService.java
  src/main/java/kosta/main/exchangehistories/controller/ExchangeHistoriesController.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoriesResponseDTO.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryCreateDTO.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryResponseDTO.java
  src/main/java/kosta/main/exchangehistories/dto/ItemHistoryDTO.java
  src/main/java/kosta/main/exchangehistories/entity/ExchangeHistory.java
  src/main/java/kosta/main/exchangehistories/repository/ExchangeHistoriesRepository.java
  src/main/java/kosta/main/exchangehistories/service/ExchangeHistoriesService.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, 기능개선, Backend, 창민

#200 Test: 입찰 컨트롤러 테스트 전체 구현, RestDocs 추가
  src/docs/asciidoc/index.adoc
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidListResponseDTO.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/test/java/kosta/main/bids/BidStubData.java
  src/test/java/kosta/main/bids/controller/BidControllerTest.java
  src/test/java/kosta/main/communityposts/controller/CommunityPostsControllerTest.java
Labels: 성수, Backend, 테스트, 문서

#205 Feat : 채팅 상세 내역에 메시지 20개씩만 전송하는 Pageable 적용
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/chats/controller/ChatsController.java
  src/main/java/kosta/main/chats/dto/ChatIdDTO.java
  src/main/java/kosta/main/chats/dto/ChatIdResponseDTO.java
  src/main/java/kosta/main/chats/dto/ChatMessageResponseDTO.java
  src/main/java/kosta/main/chats/dto/ChatRoomEventDTO.java
  src/main/java/kosta/main/chats/repository/ChatsRepository.java
  src/main/java/kosta/main/chats/service/ChatsService.java
Labels: 기능개선, Backend, 창민

#208 Fix : Pageable 순서 ASC로 변경
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
Labels: 버그 수정, Backend, 창민

#211 Fix : Pageable 순서 DESC로 변경
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
Labels: 기능개선, Backend, 창민

#212 Update ChatRoomsController.java 파일 DESC로 변경
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
Labels: 버그 수정, Backend, 창민

#213 Fix: 대댓글 방식 변경 및 테스트 변경
  src/main/java/kosta/main/comments/controller/CommentsController.java
  src/main/java/kosta/main/comments/dto/CommentChildDTO.java
  src/main/java/kosta/main/comments/dto/CommentListDTO.java
  src/main/java/kosta/main/comments/dto/CommentParentDTO.java
  src/main/java/kosta/main/comments/repository/CommentsRepositoryCustom.java
  src/main/java/kosta/main/comments/service/CommentsService.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/test/java/kosta/main/comments/controller/CommentStubData.java
  src/test/java/kosta/main/comments/controller/CommentsControllerTest.java
Labels: 기능개선, 성수, Backend, 테스트

#214 207 testdocs 교환 내역 컨트롤러 테스트 코드 및 restdocs 작성
  src/docs/asciidoc/index.adoc
  src/main/java/kosta/main/exchangehistories/controller/ExchangeHistoriesController.java
  src/main/java/kosta/main/exchangehistories/repository/ExchangeHistoriesRepository.java
  src/main/java/kosta/main/exchangehistories/service/ExchangeHistoriesService.java
  src/main/java/kosta/main/global/error/exception/CommonErrorCode.java
  src/test/java/kosta/main/exchangehistories/ExchangeHistoriesStubData.java
  src/test/java/kosta/main/exchangehistories/controller/ExchangeHistoriesControllerTest.java
Labels: 기능개선, 성수, Backend, 테스트, 문서

#216 Feat : 카카오 API 추가 및 채팅 오류 수정
  .gitignore
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/exchangeposts/service/KakaoAPI.java
  src/main/resources/application-API-KEY.properties
Labels: 버그 수정, 기능개선, Backend, 창민

#223 Feat : 새로운 브런치 분기전 Push
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/exchangeposts/service/KakaoAPI.java
Labels: 기능추가, 기능개선, Backend, 창민

#225 Fix : 채팅방 생성시 DTO 변경 : 기존 3개의 데이터에서 BidId 하나만 받도록 변경
  src/main/java/kosta/main/chatrooms/dto/CreateChatRoomDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
Labels: 기능개선, Backend, 창민

#228 Feat : 교환 게시글 작성시 받았던 주소를 활용해 XY 좌표도 함께 저장
  build.gradle
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/exchangeposts/service/KakaoAPI.java
Labels: 기능추가, Backend, 창민

#230 Fix : 채팅방 생성시 Default 메세지 생성
  src/main/java/kosta/main/chatrooms/entity/ChatRoom.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
Labels: 버그 수정, Backend, 창민

#233 198 feat 회원가입 시 이메일 본인 확인 기능 구현 1
  src/main/java/kosta/main/email/controller/EmailController.java
  src/main/java/kosta/main/email/dto/EmailCheckDto.java
  src/main/java/kosta/main/email/dto/EmailSendDto.java
  src/main/java/kosta/main/email/entity/Emails.java
  src/main/java/kosta/main/email/repository/EmailsRepository.java
  src/main/java/kosta/main/email/service/EmailSendService.java
  src/main/java/kosta/main/global/error/exception/CommonErrorCode.java
Labels: 기능추가, Backend, 윤진

#234 227 fix 물물교환 게시글 상세 조회 발생문제 확인 및 해결
  src/docs/asciidoc/index.adoc
  src/main/java/kosta/main/bids/entity/Bid.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/exchangehistories/entity/ExchangeHistory.java
  src/main/java/kosta/main/exchangehistories/repository/ExchangeHistoriesRepository.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/test/java/kosta/main/exchangeposts/controller/ExchangePostsControllerTest.java
Labels: 버그 수정, 성수, 버그 발견, Backend

#236 232 fix 채팅 내역 불러 오는 순서 변경 교환 게시글 목록에 응답 시간 변경
  src/main/java/kosta/main/chatrooms/dto/ChatRoomResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostCreateDTO.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostListDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
Labels: 기능개선, Backend, 창민

#237 Fix: 테스트시 발생하는 문제 해결
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostListDTO.java
  src/test/java/kosta/main/exchangeposts/ExchangePostStubData.java
  src/test/java/kosta/main/exchangeposts/controller/ExchangePostsControllerTest.java
  src/test/java/kosta/main/exchangeposts/service/ExchangePostsServiceTest.java
Labels: 버그 수정, 성수, 버그 발견, Backend, 테스트

#238 Fix : Bid isOwner 문제 해결 / 교환 게시글 작성자만 대화하기 가능
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/chatrooms/controller/ChatRoomsController.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
Labels: 버그 수정, Backend, 창민

#239 235 feat 아이디 찾기 기능 구현
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/UserEmailDTO.java
  src/main/java/kosta/main/users/dto/UserFindIdDTO.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, Backend, 윤진

#244 Feat : 지도에 가져올 교환 게시글 목록 응답 API / 위치 데이터명 변경
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostListForMapDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/test/java/kosta/main/exchangeposts/ExchangePostStubData.java
Labels: 기능추가, 기능개선, Backend, 창민

#246 Fix : URL 명 변경
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
Labels: wontfix, Backend, 창민

#245 242 feat 비밀번호 찾기 기능 구현
  src/main/java/kosta/main/email/controller/EmailController.java
  src/main/java/kosta/main/email/service/EmailSendService.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/UserFindPasswordDTO.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, 성수, Backend, 윤진

#249 Fix 테스트 코드 수정
  src/main/java/kosta/main/bids/dto/BidDetailResponseDTO.java
  src/main/java/kosta/main/comments/dto/CommentChildDTO.java
  src/main/java/kosta/main/comments/dto/CommentParentDTO.java
  src/main/java/kosta/main/comments/repository/CommentsRepositoryImpl.java
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostResponseDTO.java
  src/main/java/kosta/main/global/audit/Auditable.java
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/dto/ItemDetailResponseDTO.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/request/UserCreateDTO.java
  src/main/java/kosta/main/users/dto/request/UserEmailDTO.java
  src/main/java/kosta/main/users/dto/request/UserFindIdDTO.java
  src/main/java/kosta/main/users/dto/request/UserFindPasswordDTO.java
  src/main/java/kosta/main/users/dto/request/UserUpdateDTO.java
  src/main/java/kosta/main/users/dto/response/UserAllProfileResponseDTO.java
  src/main/java/kosta/main/users/dto/response/UserBidResponseDTO.java
  src/main/java/kosta/main/users/dto/response/UserCommentResponseDTO.java
  src/main/java/kosta/main/users/dto/response/UserCreateResponseDTO.java
  src/main/java/kosta/main/users/dto/response/UserItemResponseDTO.java
  src/main/java/kosta/main/users/dto/response/UsersResponseDTO.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/repository/UsersRepository.java
  src/main/java/kosta/main/users/repository/UsersRepositoryCustom.java
  src/main/java/kosta/main/users/repository/UsersRepositoryImpl.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/test/java/kosta/main/exchangeposts/controller/ExchangePostsControllerTest.java
  src/test/java/kosta/main/items/controller/ItemsControllerTest.java
  src/test/java/kosta/main/users/UserStubData.java
  src/test/java/kosta/main/users/controller/UsersControllerTest.java
  src/test/java/kosta/main/users/repository/UsersRepositoryImplTest.java
  src/test/java/kosta/main/users/service/UsersServiceTest.java
Labels: Backend

#248 231 feat 교환 게시글 지도 출력 및 데이터 수정
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/repository/ExchangePostsRepository.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
Labels: 기능추가, 기능개선, Backend, 창민

#255 Fix : 채팅 내역에 Status 추가
  src/main/java/kosta/main/chatrooms/dto/ChatRoomEnterResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
Labels: 기능개선, Backend, 창민

#257 Fix : 채팅 내역에 Bid ID 추가
  src/main/java/kosta/main/chatrooms/dto/ChatRoomEnterResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
Labels: 기능개선, Backend, 창민

#259 Fix : 채팅 내역에 isOwner 추가
  src/main/java/kosta/main/chatrooms/dto/ChatRoomEnterResponseDTO.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
Labels: 기능개선, Backend, 창민

#268 Feat: 커뮤니티 페이지 상세보기 구현
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostDetailDTO.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostListDTO.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/test/java/kosta/main/communityposts/CommunityPostStubData.java
  src/test/java/kosta/main/communityposts/controller/CommunityPostsControllerTest.java
Labels: 기능개선, 성수, Backend

#270 264 feat 남은 기능 구현 하기 1일차
  src/main/java/kosta/main/communityposts/repository/CommunityPostsRepository.java
  src/main/java/kosta/main/exchangeposts/repository/ExchangePostsRepository.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/response/UserCommunityPostResponseDTO.java
  src/main/java/kosta/main/users/dto/response/UserExchangePostResponseDTO.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, Backend, 창민

#274 [Feat] Front 요청데이터 수정
  src/main/java/kosta/main/email/controller/EmailController.java
Labels: 기능개선, Backend, 윤진

#276 Fix : 채팅방 나가기 NPE 방지 추가
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
Labels: wontfix, Backend, 창민

#298 [Feat] 본인이 차단한 사람들 리스트 제공 기능 추가
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, Backend, 윤진

#300 279 feat 본인이 차단한 사람들 리스트 제공 기능 추가 1
  src/main/java/kosta/main/blockedusers/dto/BlockedUserResponseDTO.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능추가, Backend, 윤진

#318 Fix : 각종 문제들 해결
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/chatrooms/service/ChatRoomService.java
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/repository/CommunityPostsRepository.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/dibs/service/DibsService.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDetailDTO.java
  src/main/java/kosta/main/exchangeposts/repository/ExchangePostsRepository.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/global/error/exception/CommonErrorCode.java
  src/main/java/kosta/main/items/dto/ItemDetailResponseDTO.java
  src/main/java/kosta/main/items/dto/ItemPageDTO.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/response/UsersResponseDTO.java
  src/main/java/kosta/main/users/repository/UsersRepositoryImpl.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: Backend, 창민

#322 Fix : 각종 문제들 해결 2
  src/main/java/kosta/main/comments/dto/CommentChildDTO.java
  src/main/java/kosta/main/comments/dto/CommentDTO.java
  src/main/java/kosta/main/comments/dto/CommentParentDTO.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostDetailDTO.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostListDTO.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostResponseDTO.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoriesResponseDTO.java
  src/main/java/kosta/main/exchangehistories/service/ExchangeHistoriesService.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/repository/ExchangePostsRepository.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/users/dto/request/UserUpdateDTO.java
  src/main/java/kosta/main/users/service/UsersService.java
Labels: 기능개선, Backend, 창민

#327 [Feat] 물건 검색 수정 로직 변경(제목, 내용, 카테고리)
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
Labels: 기능개선, Backend, 윤진
