Repository KostaMiniProject/MainProject-Back, pull requests merged in 2023-11, with the labels that each got.

#2 Config: 기능 기반 패키지 구조 설정
  src/main/java/kosta/main/bid/testfile.java
  src/main/java/kosta/main/blockedusers/testfile.java
  src/main/java/kosta/main/category/testfile.java
  src/main/java/kosta/main/chatroom/testfile.java
  src/main/java/kosta/main/chats/testfile.java
  src/main/java/kosta/main/comments/testfile.java
  src/main/java/kosta/main/communityposts/testfile.java
  src/main/java/kosta/main/dibs/testfile.java
  src/main/java/kosta/main/exchangehistories/testfile.java
  src/main/java/kosta/main/exchangeposts/testfile.java
  src/main/java/kosta/main/items/testfile.java
  src/main/java/kosta/main/likes/testfile.java
  src/main/java/kosta/main/reports/testfile.java
  src/main/java/kosta/main/reviews/testfile.java
  src/main/java/kosta/main/users/testfile.java
Labels: 설정변경, Backend, 동건

#9 Config: test설정용 githubaction yml 파일 추가
  .github/workflows/test.yml
Labels: 설정변경, 성수, Backend

#18 [Feat] 커뮤니티 기능 생성
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostUpdateDto.java
  src/main/java/kosta/main/communityposts/repository/CommunityPostsRepository.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/communityposts/testfile.java
Labels: 기능추가, Backend, 동건

#17 [Feat] 물건 기능 생성
  src/main/java/kosta/main/items/controller/ItemsController.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/items/service/ItemsService.java
Labels: 기능추가, Backend, 윤진

#20 Config: validation 추가
  build.gradle
Labels: 설정변경, 성수, Backend

#16 Feat : 물물교환 게시글 작성, 삭제, 상세조회, 목록조회 기능 완료
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
  src/main/java/kosta/main/exchangeposts/repository/ExchangePostsRepository.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
  src/main/java/kosta/main/users/repository/UsersRepository.java
Labels: 기능추가, Backend, 창민

#22 Hotfix: bid entity Items 추가
  src/main/java/kosta/main/bids/entity/Bid.java
Labels: 설정변경, 성수, Backend

#24 Feat : 물물교환 게시글 수정 기능 구현, 물물교환 게시글 삭제 기능 수정(Softdelete)
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
Labels: 기능개선, Backend, 창민

#30 Config:querydsl 설정 추가
  build.gradle
Labels: 설정변경, 성수, Backend

#35 Config:유저 정보 조회, 회원가입,내 정보 수정,탈퇴하기 구현
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/dto/UserCreateDto.java
  src/main/java/kosta/main/users/dto/UserCreateResponseDto.java
  src/main/java/kosta/main/users/dto/UserUpdateDto.java
  src/main/java/kosta/main/users/dto/UsersResponseDto.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/repository/UsersRepository.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/main/java/kosta/main/utils/CustomBeanUtils.java
Labels: 기능추가, 성수, Backend

#37 Test:유저 정보 조회, 회원가입,내 정보 수정,탈퇴하기 테스트 코드 구현
  src/main/java/kosta/main/users/dto/UserCreateDto.java
  src/main/java/kosta/main/users/dto/UserUpdateDto.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/test/java/kosta/main/users/UserStubData.java
  src/test/java/kosta/main/users/controller/UsersControllerTest.java
  src/test/java/kosta/main/users/service/UsersServiceTest.java
Labels: 성수, Backend, 테스트

#38 36 Refactor 유저 기능 변경
  src/main/java/kosta/main/config/QuerydslConfig.java
  src/main/java/kosta/main/users/dto/UserCreateDto.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/repository/UsersRepositoryCustom.java
  src/main/java/kosta/main/users/repository/UsersRepositoryImpl.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/main/java/kosta/main/utils/CustomBeanUtils.java
  src/test/java/kosta/main/users/UserStubData.java
  src/test/java/kosta/main/users/repository/UsersRepositoryImplTest.java
  src/test/java/kosta/main/users/service/UsersServiceTest.java
Labels: 기능개선, 성수, 기능제거, Backend

#43 39 feat 유저관련 기능 구현 2
  build.gradle
  src/main/java/kosta/main/bids/entity/Bid.java
  src/main/java/kosta/main/blockedusers/entity/BlockedUser.java
  src/main/java/kosta/main/blockedusers/repository/BlockedUsersRepository.java
  src/main/java/kosta/main/blockedusers/testfile.java
  src/main/java/kosta/main/categories/entity/Category.java
  src/main/java/kosta/main/chatrooms/entity/ChatRoom.java
  src/main/java/kosta/main/chats/entity/Chat.java
  src/main/java/kosta/main/comments/entity/Comment.java
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/dibs/dto/DibResponseDto.java
  src/main/java/kosta/main/dibs/entity/Dib.java
  src/main/java/kosta/main/dibs/repository/DibsRepository.java
  src/main/java/kosta/main/exchangehistories/dto/ExchangeHistoryResponseDto.java
  src/main/java/kosta/main/exchangehistories/entity/ExchangeHistory.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
  src/main/java/kosta/main/global/audit/Auditable.java
  src/main/java/kosta/main/global/config/QuerydslConfig.java
  src/main/java/kosta/main/global/config/SecurityConfig.java
  src/main/java/kosta/main/items/entity/Item.java
  src/main/java/kosta/main/likes/entity/Like.java
  src/main/java/kosta/main/reports/dto/CreateReportDto.java
  src/main/java/kosta/main/reports/entity/Report.java
  src/main/java/kosta/main/reports/repository/ReportsRepository.java
  src/main/java/kosta/main/reports/testfile.java
  src/main/java/kosta/main/reviews/entity/Review.java
  src/main/java/kosta/main/users/controller/UsersController.java
  src/main/java/kosta/main/users/entity/User.java
  src/main/java/kosta/main/users/repository/UsersRepository.java
  src/main/java/kosta/main/users/service/UsersService.java
  src/main/java/kosta/main/users/testfile.java
  src/test/java/kosta/main/users/controller/UsersControllerTest.java
  src/test/java/kosta/main/users/repository/UsersRepositoryImplTest.java
  src/test/java/kosta/main/users/service/UsersServiceTest.java
Labels: 기능추가, 설정변경, 성수, Backend

#31 Feat : Item, ExchangePost, Bid의 상호 status 변경 (미완성)
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidsDto.java
  src/main/java/kosta/main/bids/entity/Bid.java
  src/main/java/kosta/main/bids/repository/BidRepository.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/items/entity/Item.java
Labels: 기능추가, 기능개선, Backend, 창민

#45 Fix: 에러나는부분 변경
  src/main/java/kosta/main/items/dto/ItemUpdateDto.java
Labels: 버그 수정, Backend

#46 Fix: 에러나는부분 변경
  src/main/java/kosta/main/items/entity/Item.java
Labels: 버그 수정, 성수, Backend

#50 Config: timezone 설정위해 DockerFile 변경
  Dockerfile
Labels: 설정변경, 성수, Backend

#52 Config: submodule 자동업데이트 githubAcition 파일추가
  .github/workflows/submodule.yml
Labels: 설정변경, 성수, Backend

#63 Config: 서버 Cors 허용 도메인 추가
  src/main/java/kosta/main/global/config/SecurityConfig.java
Labels: 설정변경, 성수, Backend

#57 Refactor : 코드리뷰에서 나온 수정 사항들 반영 (ExchangePost, Bid)
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidCreateDto.java
  src/main/java/kosta/main/bids/dto/BidUpdateDto.java
  src/main/java/kosta/main/bids/entity/Bid.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
Labels: Backend, 창민, 리팩터링

#66 Feat : 교환게시글 목록 조회 프론트와 데이터형태 동일하게 변경완료
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidListDTO.java
  src/main/java/kosta/main/bids/repository/BidRepository.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDetailDTO.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostListDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/items/entity/Item.java
  src/main/java/kosta/main/items/repository/ItemsRepository.java
Labels: 기능개선, Backend, 창민

#75 [Feat] 커뮤니티 기능 생성 좋아요 기능
  src/main/java/kosta/main/communityposts/controller/CommunityPostsController.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostResponseDto.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostSelectDto.java
  src/main/java/kosta/main/communityposts/dto/CommunityPostUpdateDto.java
  src/main/java/kosta/main/communityposts/entity/CommunityPost.java
  src/main/java/kosta/main/communityposts/service/CommunityPostsService.java
  src/main/java/kosta/main/likes/entity/Like.java
  src/main/java/kosta/main/likes/repository/LikesRepository.java
Labels: 기능추가, Backend

#78 Feat : Bid status에 예약중 추가
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidCompleteDTO.java
  src/main/java/kosta/main/bids/dto/BidDetailResponseDTO.java
  src/main/java/kosta/main/bids/dto/BidResponseDTO.java
  src/main/java/kosta/main/bids/dto/BidUpdateDTO.java
  src/main/java/kosta/main/bids/dto/BidUpdateResponseDTO.java
  src/main/java/kosta/main/bids/dto/BidsDto.java
  src/main/java/kosta/main/bids/entity/Bid.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/exchangeposts/entity/ExchangePost.java
Labels: 설정변경, Backend, 창민

#79 Feat : Bid 관련 기능 개선 및 추가
  src/main/java/kosta/main/bids/controller/BidController.java
  src/main/java/kosta/main/bids/dto/BidCompleteDTO.java
  src/main/java/kosta/main/bids/dto/BidListDTO.java
  src/main/java/kosta/main/bids/dto/BidReserveDTO.java
  src/main/java/kosta/main/bids/dto/BidUpdateResponseDTO.java
  src/main/java/kosta/main/bids/service/BidService.java
  src/main/java/kosta/main/exchangeposts/controller/ExchangePostsController.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDTO.java
  src/main/java/kosta/main/exchangeposts/dto/ExchangePostDeleteDTO.java
  src/main/java/kosta/main/exchangeposts/service/ExchangePostsService.java
  src/main/java/kosta/main/items/entity/Item.java
  src/main/java/kosta/main/likes/testfile.java
Labels: 기능추가, 기능개선, Backend, 창민
